export type PricingGroup = "제작" | "케어" | "광고";

export type PricingPlan = {
  id: string;
  group: PricingGroup;
  name: string;
  subtitle: string;
  monthly: boolean;
  originalPrice: number;
  originalFrom: boolean;
  salePrice: number;
  saleFrom: boolean;
  features: string[];
  highlighted: boolean;
  crown: boolean;
};

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "start",
    group: "제작",
    name: "START 랜딩페이지",
    subtitle: "랜딩페이지 1페이지",
    monthly: false,
    originalPrice: 498000,
    originalFrom: false,
    salePrice: 249000,
    saleFrom: false,
    features: ["3~4일 빠른 제작", "반응형(PC·모바일)", "문의폼 연동", "기본 SEO"],
    highlighted: false,
    crown: false,
  },
  {
    id: "grow",
    group: "제작",
    name: "GROW 홈페이지",
    subtitle: "홈페이지 5페이지",
    monthly: false,
    originalPrice: 1980000,
    originalFrom: false,
    salePrice: 990000,
    saleFrom: false,
    features: ["1주 제작", "반응형", "문의폼 연동", "카카오톡 상담연동", "기본 SEO"],
    highlighted: false,
    crown: false,
  },
  {
    id: "master",
    group: "제작",
    name: "MASTER 프리미엄",
    subtitle: "홈페이지+랜딩페이지",
    monthly: false,
    originalPrice: 2980000,
    originalFrom: false,
    salePrice: 1490000,
    saleFrom: false,
    features: [
      "1~2주",
      "반응형",
      "프리미엄 디자인",
      "예약·문의 시스템",
      "SEO 최적화",
      "광고 전환 구조 설계",
    ],
    highlighted: true,
    crown: true,
  },
  {
    id: "we-care",
    group: "케어",
    name: "WE CARE",
    subtitle: "기본 · 월 관리",
    monthly: true,
    originalPrice: 170000,
    originalFrom: false,
    salePrice: 89000,
    saleFrom: true,
    features: ["유지보수 월1", "블로그 월1", "인스타 월4(주1)", "스레드 월4(주1)", "SEO 상단등록"],
    highlighted: false,
    crown: false,
  },
  {
    id: "flow-care",
    group: "케어",
    name: "FLOW CARE",
    subtitle: "성장 · 월 관리",
    monthly: true,
    originalPrice: 378000,
    originalFrom: true,
    salePrice: 189000,
    saleFrom: true,
    features: [
      "유지보수 월3",
      "인스타 월8(주2)",
      "스레드 월8(주2)",
      "블로그 월2",
      "네이버 키워드 세팅 할인(149,000→79,000)",
      "당근 키워드 50% 할인(79,000→39,000)",
      "문의 개선",
      "SEO 상단등록",
    ],
    highlighted: false,
    crown: false,
  },
  {
    id: "weflow-care",
    group: "케어",
    name: "WEFLOW CARE",
    subtitle: "올인원 · 월 관리",
    monthly: true,
    originalPrice: 678000,
    originalFrom: true,
    salePrice: 339000,
    saleFrom: true,
    features: [
      "유지보수 무제한",
      "블로그 월4(주1)",
      "인스타 월12(주3)",
      "스레드 월12(주3)",
      "네이버 키워드·당근 플레이스 광고 세팅 무료",
      "월 성과 체크",
      "랜딩 개선",
      "광고관리",
      "SEO 최적화",
    ],
    highlighted: true,
    crown: true,
  },
  {
    id: "naver-ad",
    group: "광고",
    name: "네이버 광고",
    subtitle: "키워드 셋팅",
    monthly: false,
    originalPrice: 298000,
    originalFrom: false,
    salePrice: 149000,
    saleFrom: true,
    features: [
      "키워드 분석",
      "광고 세팅 지원",
      "광고 문구 제작",
      "문의 구조 연결",
      "채널 연동 지원",
      "성과 최적화",
    ],
    highlighted: false,
    crown: false,
  },
  {
    id: "danggn-ad",
    group: "광고",
    name: "당근 플레이스 광고",
    subtitle: "지역 키워드 셋팅",
    monthly: false,
    originalPrice: 158000,
    originalFrom: false,
    salePrice: 79000,
    saleFrom: true,
    features: [
      "지역 키워드 분석",
      "광고 세팅 지원",
      "광고 문구 제작",
      "지역 타겟 설정",
      "랜딩 연결 지원",
      "성과 최적화",
    ],
    highlighted: false,
    crown: false,
  },
];
